site_name: Lunali Documentation
site_url: https://lunali.readthedocs.io
nav:
  - Home: index.md
  - Power Types: types/power_types.md
  - Action Types:
      - Entity Action Types: types/entity_action_types.md
  - Backgrounds: types/origin_backgrounds.md
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: images/lunali_title.png
  favicon: images/lunali.png
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/pQgEvEYpyq
      name: My Discord!
markdown_extensions:
  - toc:
      separator: "_"
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - stylesheets/extra.css
